[versions]
agp = "8.5.2"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
mainActivity = "1.9.1"
constraintlayout = "2.2.1"
libraryPlugin = "8.0.2"
simpleHttpRequest = "1.0"
glide = "4.15.1"
glideCompiler = "4.15.1"
activity = "1.12.2"
gson = "2.10.1"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
#mainActivity = { group = "androidx.mainActivity", name = "mainActivity", version.ref = "mainActivity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
simpleHttpRequest = { group = "com.github.androdocs", name = "Simple-HTTP-Request", version.ref = "simpleHttpRequest" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
glideCompiler = { group = "com.github.bumptech.glide", name = "compiler", version.ref = "glideCompiler" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "libraryPlugin" }

